import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import styles from './style.module.scss';
const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Procedural Generation Challenge',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body style={{margin: 0}} className={`${inter.className} ${styles.main}`}>{children}</body>
    </html>
  )
}
